window.DEFAULTS = {
  severe: 8.0, severe_pad: 0.2, severe_merge: 0.2, ramp: 0.3,
  light_cutoff: 25.0, strong_cutoff: 2.5, noise_low: 1.5, noise_high: 5.0,
  noise_band: [30.0, 180.0], noise_window: 100.0,
  hampel_window: 7, hampel_sigma: 6.0, optical_cutoff: 8.0,
  handback_cutoff: null, fast_handback: [100.0, 250.0],
  gyro_trust_noise: [200.0, 300.0],
  patch_pad: 0.5, patch_merge: 1.0, optical_noise: null,
  fast_wide_cutoff: 0.0, fast_wide_ramp: [150.0, 300.0],
  fast_wide_accel: 1500.0, anchor_mode: false, anchor_cutoff: 1.5,
};
window.M4 = Object.assign({}, window.DEFAULTS, { fast_wide_cutoff: 16.0 });

window.HELP = {
  severe: "deg/s 30-180 Hz band-RMS above which orientation is replaced with integrated optical motion (default 8)",
  severe_pad: "s, padding around each severe burst (default 0.2)",
  severe_merge: "s, gap below which severe bursts merge (default 0.2)",
  ramp: "s, slerp cross-fade to the raw path at burst edges (default 0.3)",
  light_cutoff: "Hz, zero-phase low-pass applied in clean sections (default 25; real motion above 20 Hz is negligible per video ground truth)",
  strong_cutoff: "Hz, low-pass blended in during noise bursts (default 2.5; video ground-truth analysis showed phantom gyro motion extends down to ~3 Hz while real motion above 3 Hz is tiny)",
  noise_low: "deg/s band-RMS where patching starts blending in (default 1.5; calm-flight floor is ~1)",
  noise_high: "deg/s band-RMS where patching is fully active (default 5)",
  noise_band: "Hz band used to measure noise level (default 30 180)",
  noise_window: "ms rolling window for the noise estimate (default 100)",
  hampel_window: "Hampel half-window in samples (default 7)",
  hampel_sigma: "Hampel outlier threshold in sigmas (default 6)",
  optical_cutoff: "Hz, bandwidth of patched sections: applied to both video-measured motion and handed-back gyro (default 8)",
  fast_handback: "deg/s ramp over which patched sections switch from optical data back to band-limited gyro during fast motion, where gyro SNR is high and optical flow degrades (default 100 250)",
  gyro_trust_noise: "deg/s ramp on a patch segment's PEAK 30-180 Hz band-RMS above which the fast-handback rate estimate stops trusting the gyro and uses min(gyro, optical) instead; in such monster bursts the phantom inflates the gyro rate estimate and would wrongly hand orientation back to the noisy gyro (default 200 300)",
  patch_pad: "s, padding added around each optical-patch interval (default 0.5)",
  patch_merge: "s, gap below which adjacent patch intervals merge (default 1.0)",
  optical_noise: "deg/s band-RMS ramp that triggers OPTICAL substitution (separate, higher threshold than --noise-low/high; mild zones then keep --strong-cutoff filtered gyro instead of optical). Default: same as noise-low/high",
  handback_cutoff: "Hz, bandwidth of gyro handed back during fast motion inside patches (default: --optical-cutoff)",
  fast_wide_cutoff: "Hz, wider handback bandwidth blended in during very fast motion where mid-band gyro is real-dominated. OFF by default; 16 recovers more sharp-turn/flip crispness (2-8/8-15 Hz) at the cost of ~1.5 deg/s extra 15-30 Hz flick shake - a measured trade-off, eyeball eval_M4 vs eval_M2 to choose",
  fast_wide_ramp: "deg/s ramp over which the wider handback engages (default 150 300)",
  fast_wide_accel: "deg/s^2 above which the wider handback fades back out (snap transitions corrupt the mid-band gyro; default 1500, 0 disables the gate)",
  anchor_mode: "in noise bursts keep --strong-cutoff band-limited gyro and use optical only as a low-frequency drift anchor (see --anchor-cutoff), instead of replacing the motion with optical rates",
  anchor_cutoff: "Hz, bandwidth of the optical drift anchor in --anchor-mode (default 1.5)",
};

// field descriptors driving the settings form
window.FIELDS = [
  // group, key, label, kind: "num" | "pair" | "pair_opt" | "num_opt" | "bool"
  ["Repair thresholds", "severe", "Severe threshold (°/s)", "num"],
  ["Repair thresholds", "severe_pad", "Burst padding (s)", "num"],
  ["Repair thresholds", "severe_merge", "Burst merge gap (s)", "num"],
  ["Repair thresholds", "ramp", "Edge cross-fade (s)", "num"],
  ["Filter tuning", "light_cutoff", "Light low-pass (Hz)", "num"],
  ["Filter tuning", "strong_cutoff", "Strong low-pass (Hz)", "num"],
  ["Filter tuning", "noise_low", "Noise blend start (°/s)", "num"],
  ["Filter tuning", "noise_high", "Noise blend full (°/s)", "num"],
  ["Filter tuning", "noise_band", "Noise band (Hz lo/hi)", "pair"],
  ["Filter tuning", "noise_window", "Noise window (ms)", "num"],
  ["Filter tuning", "hampel_window", "Hampel half-window", "num"],
  ["Filter tuning", "hampel_sigma", "Hampel sigma", "num"],
  ["Optical", "optical_cutoff", "Optical bandwidth (Hz)", "num"],
  ["Optical", "handback_cutoff", "Handback cutoff (Hz, blank = optical)", "num_opt"],
  ["Optical", "fast_handback", "Fast handback ramp (°/s lo/hi)", "pair"],
  ["Optical", "gyro_trust_noise", "Gyro-trust noise ramp (°/s lo/hi)", "pair"],
  ["Optical", "patch_pad", "Patch padding (s)", "num"],
  ["Optical", "patch_merge", "Patch merge gap (s)", "num"],
  ["Optical", "optical_noise", "Optical threshold (°/s lo/hi, blank = noise)", "pair_opt"],
  ["Optical", "fast_wide_cutoff", "Fast-wide cutoff (Hz, 0 = off)", "num"],
  ["Optical", "fast_wide_ramp", "Fast-wide ramp (°/s lo/hi)", "pair"],
  ["Optical", "fast_wide_accel", "Fast-wide accel gate (°/s², 0 = off)", "num"],
  ["Optical", "anchor_mode", "Anchor mode (experimental)", "bool"],
  ["Optical", "anchor_cutoff", "Anchor cutoff (Hz)", "num"],
];
